/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_fabiohenriquez;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author FABIO
 */
public class principal extends javax.swing.JFrame {

    
    
    public principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        usuario_normal = new javax.swing.JFrame();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_area = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        publico = new javax.swing.JRadioButton();
        privado = new javax.swing.JRadioButton();
        amigos = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_publicaciones = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        m_nombre = new javax.swing.JTextField();
        m_correo = new javax.swing.JTextField();
        m_usuario = new javax.swing.JTextField();
        m_contraseña = new javax.swing.JTextField();
        m_date = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        m_imagen = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        arbol_solicitudes = new javax.swing.JTree();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        arbol_amigos = new javax.swing.JTree();
        jPanel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton11 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        mis_publicaciones = new javax.swing.JTree();
        jLabel27 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        usuario_administrador = new javax.swing.JFrame();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        usuario_listas = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        mensajes_mensajes = new javax.swing.JList<>();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        ppm_publicacion = new javax.swing.JPopupMenu();
        enviar_comentario = new javax.swing.JMenuItem();
        enviar_respuesta = new javax.swing.JMenuItem();
        enviar_problema = new javax.swing.JMenuItem();
        agregar_comentario = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        area_comentario = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        agregar_respuesta = new javax.swing.JDialog();
        agregar_problema = new javax.swing.JDialog();
        ppm_bloquear_usuario = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        ppm_bloquear_mensajes = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        ppm_solicitudes = new javax.swing.JPopupMenu();
        agregar_amigo = new javax.swing.JMenuItem();
        ppm_amigos = new javax.swing.JPopupMenu();
        eliminar_amigo = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        l_nombre = new javax.swing.JTextField();
        l_contraseña = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        r_correo = new javax.swing.JTextField();
        r_usuario = new javax.swing.JTextField();
        r_contraseña = new javax.swing.JTextField();
        r_nombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        r_foto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        date_chooser = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        admin = new javax.swing.JRadioButton();
        normal = new javax.swing.JRadioButton();

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Realizar Publicacion");

        text_area.setColumns(20);
        text_area.setRows(5);
        jScrollPane1.setViewportView(text_area);

        jLabel12.setText("Privacidad");

        buttonGroup2.add(publico);
        publico.setText("Publico");

        buttonGroup2.add(privado);
        privado.setText("Privado");

        buttonGroup2.add(amigos);
        amigos.setText("Amigos");

        jButton4.setText("Publicar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(36, 36, 36)
                                .addComponent(publico)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(privado)
                                        .addGap(28, 28, 28)
                                        .addComponent(amigos, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(publico)
                    .addComponent(privado)
                    .addComponent(amigos))
                .addGap(53, 53, 53)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Publicaciones", jPanel3);

        lista_publicaciones.setModel(new DefaultListModel());
        lista_publicaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_publicacionesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lista_publicaciones);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Lista de Publicaciones");

        jButton5.setText("Actualizar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 360, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(59, 59, 59))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jButton5))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Listar Publicaciones", jPanel4);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Nombre");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Correo");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Nombre de Usuario");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Contraseña");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Fecha de Nacimiento");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Foto de Perfil");

        jButton9.setText("Cargar Foto");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        m_imagen.setText("imagen");

        jButton10.setText("Guardar y Modificar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(49, 49, 49)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(m_contraseña, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_usuario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_correo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_date, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(m_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addGap(249, 249, 249))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(m_nombre)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(m_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(m_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(m_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(m_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(m_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jTabbedPane2.addTab("Mi Perfil", jPanel6);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("solicitudes");
        arbol_solicitudes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbol_solicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbol_solicitudesMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(arbol_solicitudes);

        jLabel24.setText("Solicitudes de Amistad");

        jLabel25.setText("Amigos");

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("amigos");
        arbol_amigos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbol_amigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbol_amigosMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(arbol_amigos);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(264, 264, 264))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel24))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel25)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Solicitudes de Amistad", jPanel7);

        jLabel26.setText("Problemas");

        jList1.setModel(new DefaultListModel());
        jScrollPane8.setViewportView(jList1);

        jButton11.setText("Responder");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel26))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Problemas", jPanel8);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("publicaciones");
        mis_publicaciones.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane9.setViewportView(mis_publicaciones);

        jLabel27.setText("Mis publicaciones");

        jButton12.setText("Ver mis publicaciones");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel27))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jButton12)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Mis publicaciones", jPanel9);

        jButton13.setText("NO PRESIONAR");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        jTabbedPane2.addTab("ELIMINAR MI CUENTA", jPanel10);

        javax.swing.GroupLayout usuario_normalLayout = new javax.swing.GroupLayout(usuario_normal.getContentPane());
        usuario_normal.getContentPane().setLayout(usuario_normalLayout);
        usuario_normalLayout.setHorizontalGroup(
            usuario_normalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        usuario_normalLayout.setVerticalGroup(
            usuario_normalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jLabel15.setText("Usuarios");

        usuario_listas.setModel(new DefaultListModel());
        usuario_listas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuario_listasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(usuario_listas);

        jLabel16.setText("Mensajes");

        mensajes_mensajes.setModel(new DefaultListModel());
        mensajes_mensajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mensajes_mensajesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(mensajes_mensajes);

        jButton7.setText("Actualizar Lista");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("Actualizar Lista");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(93, 93, 93))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addGap(162, 162, 162)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Ver usuarios y Mensajes", jPanel5);

        javax.swing.GroupLayout usuario_administradorLayout = new javax.swing.GroupLayout(usuario_administrador.getContentPane());
        usuario_administrador.getContentPane().setLayout(usuario_administradorLayout);
        usuario_administradorLayout.setHorizontalGroup(
            usuario_administradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        usuario_administradorLayout.setVerticalGroup(
            usuario_administradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        enviar_comentario.setText("Enviar Comentario");
        enviar_comentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviar_comentarioActionPerformed(evt);
            }
        });
        ppm_publicacion.add(enviar_comentario);

        enviar_respuesta.setText("Enviar Respuesta");
        ppm_publicacion.add(enviar_respuesta);

        enviar_problema.setText("Enviar Problema");
        ppm_publicacion.add(enviar_problema);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Ingresar Comentario");

        area_comentario.setColumns(20);
        area_comentario.setRows(5);
        jScrollPane3.setViewportView(area_comentario);

        jButton6.setText("Agregar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout agregar_comentarioLayout = new javax.swing.GroupLayout(agregar_comentario.getContentPane());
        agregar_comentario.getContentPane().setLayout(agregar_comentarioLayout);
        agregar_comentarioLayout.setHorizontalGroup(
            agregar_comentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregar_comentarioLayout.createSequentialGroup()
                .addGroup(agregar_comentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregar_comentarioLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel14))
                    .addGroup(agregar_comentarioLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(agregar_comentarioLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        agregar_comentarioLayout.setVerticalGroup(
            agregar_comentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregar_comentarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout agregar_respuestaLayout = new javax.swing.GroupLayout(agregar_respuesta.getContentPane());
        agregar_respuesta.getContentPane().setLayout(agregar_respuestaLayout);
        agregar_respuestaLayout.setHorizontalGroup(
            agregar_respuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        agregar_respuestaLayout.setVerticalGroup(
            agregar_respuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout agregar_problemaLayout = new javax.swing.GroupLayout(agregar_problema.getContentPane());
        agregar_problema.getContentPane().setLayout(agregar_problemaLayout);
        agregar_problemaLayout.setHorizontalGroup(
            agregar_problemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        agregar_problemaLayout.setVerticalGroup(
            agregar_problemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem1.setText("Bloquear Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        ppm_bloquear_usuario.add(jMenuItem1);

        jMenuItem2.setText("Bloquear Mensaje");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        ppm_bloquear_mensajes.add(jMenuItem2);

        agregar_amigo.setText("Agregar Amigo");
        agregar_amigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_amigoActionPerformed(evt);
            }
        });
        ppm_solicitudes.add(agregar_amigo);

        eliminar_amigo.setText("jMenuItem1");
        eliminar_amigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_amigoActionPerformed(evt);
            }
        });
        ppm_amigos.add(eliminar_amigo);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Iniciar Sesion");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nombre");

        jButton3.setText("Iniciar Sesion");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(l_nombre)
                                .addComponent(l_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))))
                .addContainerGap(502, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52)
                        .addComponent(l_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(l_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("inicio de Sesion", jPanel1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Correo");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Contraseña");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Nombre de Usuario");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Foto de Perfil");

        r_foto.setText("imagen");

        jButton1.setText("Cargar Foto");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Fecha de Nacimiento");

        jButton2.setText("AGREGAR");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Usuario ");

        buttonGroup1.add(admin);
        admin.setText("Administrador");

        buttonGroup1.add(normal);
        normal.setText("Normal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel9))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(r_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(r_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(374, 374, 374)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel8)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(r_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(r_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(date_chooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(admin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(normal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(r_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(239, 239, 239))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(r_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(r_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(r_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(date_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r_contraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(46, 46, 46))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(admin)
                        .addComponent(normal))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Registro", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       JFileChooser fc = new JFileChooser();
       FileFilter filtro = new FileNameExtensionFilter("Imagenes","png,","jpg","jpeg","gif");
       fc.setFileFilter(filtro);
       File archivo;
       int op = fc.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            archivo = fc.getSelectedFile();
            Image img = Toolkit.getDefaultToolkit().createImage(archivo.getPath()).getScaledInstance(200, 217, 0);
            this.r_foto.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        //abu.cargarArchivo();
        //ArrayList<usuario_administrador> tempo_a = new ArrayList();
        //tempo_a = abu.getUsuario_administrador();
        ////////
        abun.cargarArchivo();
        //ArrayList<usuario_normal> tempo_n = new ArrayList();
        //tempo_n = abun.getU_normal();
        //
        if (admin.isSelected()) {
            tempo_a.add(new usuario_administrador(r_nombre.getText(),
            r_correo.getText(),
            r_usuario.getText(),
            date_chooser.getDate(),
            r_contraseña.getText(),
            r_foto.getIcon()));
            /*abu.setUsuario_administrador(tempo_a);
            
            try {
                abu.escribirArchivo();
            } catch (IOException ex) {
                Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
            }*/
        }else if(normal.isSelected()){
            /*tempo_n.add(new usuario_normal(r_nombre.getText(),
            r_correo.getText(),
            r_usuario.getText(),
            date_chooser.getDate(),
            r_contraseña.getText(),
            r_foto.getIcon(),1));*/
            abun.getU_normal().add(new usuario_normal(r_nombre.getText(),
            r_correo.getText(),
            r_usuario.getText(),
            date_chooser.getDate(),
            r_contraseña.getText(),
            r_foto.getIcon(),1));//setUsuario_administrador(tempo_n);
            try {
                abun.escribirArchivo();
            } catch (IOException ex) {
                Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            DefaultTreeModel m = (DefaultTreeModel) arbol_solicitudes.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            DefaultMutableTreeNode solicitudes = new DefaultMutableTreeNode(r_nombre.getText() + " | "+ r_usuario.getText());
            raiz.add(solicitudes);
            m.reload();
        }
        
        JOptionPane.showMessageDialog(this, "Usuario Registrado exitosamente ");
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       abun.cargarArchivo();
        //ArrayList<usuario_administrador> tempo_a = new ArrayList();
        //tempo_a = abu.getUsuario_administrador();
        ////////
        //abun.cargarArchivo();
        tempo_n = new ArrayList();
        tempo_n = abun.getU_normal();
        //
        if (l_nombre.getText().equals(usuario_defecto) && l_contraseña.getText().equals(contraseña)) {
            usuario_administrador.pack();
                usuario_administrador.setLocationRelativeTo(this);
                usuario_administrador.setVisible(true);
        }
        for (int i=0 ; i < tempo_n.size() ; i++) {
            if (l_nombre.getText().equals(tempo_n.get(i).getNombre_usuario()) && l_contraseña.getText().equals(tempo_n.get(i).getContraseña())) {
                usuario_normal.pack();
                usuario_normal.setLocationRelativeTo(this);
                
                usuario_normal.setVisible(true);
                //
                m_nombre.setText(tempo_n.get(i).getNombre());
                m_usuario.setText(tempo_n.get(i).getNombre_usuario());
                m_correo.setText(tempo_n.get(i).getContraseña());
                m_date.setDate(tempo_n.get(i).getFecha_naciomiento());
                m_contraseña.setText(tempo_n.get(i).getContraseña());
                m_imagen.setIcon(tempo_n.get(i).getFoto());
                //
                index_usuario_normal = i;
                //
                
            }
            
        }
        for (int i=0 ; i < tempo_a.size() ; i++) {
            if (l_nombre.getText().equals(tempo_a.get(i).getNombre_usuario()) && l_contraseña.getText().equals(tempo_a.get(i).getContraseña())) {
                usuario_administrador.pack();
                usuario_administrador.setLocationRelativeTo(this);
                usuario_administrador.setVisible(true);
                index_usuario_admin=i;
            }
        }
       
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        int privacidad=0;
        Date fecha = new Date();
        if (publico.isSelected()) {
            privacidad = 1;
        }else if(privado.isSelected()){
            privacidad = 2;
        }else if(amigos.isSelected()){
            privacidad = 3;
        }
     
        
      abun.cargarArchivo();
      tempo_n = new ArrayList();
      tempo_n = abun.getU_normal();
      //usuario_normal user;
        
      //user = abun.getU_normal().get(index_usuario_normal);
    
      //publicacion publi  = new publicacion(text_area.getText(),user,privacidad, new Date());
     
        //user.publicaciones.add(publi);
       
        usuario_normal usuario = tempo_n.get(index_usuario_normal);
        //tempo_n.get(index_usuario_normal).getPublicaciones().add(new publicacion(text_area.getText(),usuario,privacidad,new Date(),1));
       //tempo_publicaciones.add(new publicacion(text_area.getText(),usuario,privacidad,new Date(),1));
        //System.out.println(abun.getU_normal().get(index_usuario_normal).getPublicaciones());
        abun.getU_normal().get(index_usuario_normal).getPublicaciones().add(new publicacion(text_area.getText(),usuario,privacidad,new Date(),1));
        
                
                
        try {
            abun.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*try {
            System.out.println("e1");
            abun.escribirArchivo();
            System.out.println("e2");
        } catch (IOException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        ap.getPublicaciones().add(new publicacion(text_area.getText(),usuario,privacidad,new Date(),1));
        try {
            ap.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        ap.cargarArchivo();
        ArrayList<publicacion> xd = new ArrayList();
        xd = ap.getPublicaciones();
       lista_publicaciones.setModel(new DefaultListModel());
       DefaultListModel modelo1 = (DefaultListModel) lista_publicaciones.getModel(); 
            
        for (publicacion tem : xd) {
            modelo1.addElement(tem);
        }
            
        
        lista_publicaciones.setModel(modelo1);
    }//GEN-LAST:event_jButton5MouseClicked

    private void lista_publicacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_publicacionesMouseClicked
        if (evt.isMetaDown()) {
            ppm_publicacion.show(evt.getComponent(), evt.getX(),evt.getY());
            index_publicacion = lista_publicaciones.getSelectedIndex();
        }
    }//GEN-LAST:event_lista_publicacionesMouseClicked

    private void enviar_comentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviar_comentarioActionPerformed
        agregar_comentario.pack();
                agregar_comentario.setLocationRelativeTo(this);
                agregar_comentario.setVisible(true);
    }//GEN-LAST:event_enviar_comentarioActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        ap.cargarArchivo();
        for (publicacion t : ap.getPublicaciones()) {
            if(t instanceof respuesta){
                ((respuesta)ap.getPublicaciones().get(lista_publicaciones.getSelectedIndex())).getComentarios().add(new comentario(area_comentario.getText()));
            }
            
        }
        try {
            ap.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        usuario_listas.setModel(new DefaultListModel());
        DefaultListModel modelo1 = (DefaultListModel) usuario_listas.getModel();
        abun.cargarArchivo();
        tempo_n = new ArrayList();
        tempo_n = abun.getU_normal();
        for (usuario_normal tem : tempo_n) {
            modelo1.addElement(tem);
        }
        usuario_listas.setModel(modelo1);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        mensajes_mensajes.setModel(new DefaultListModel());
        DefaultListModel modelo1 = (DefaultListModel) mensajes_mensajes.getModel();
        ap.cargarArchivo();
        tempo_publicaciones = new ArrayList();
        tempo_publicaciones = ap.getPublicaciones();
        for (publicacion tem : tempo_publicaciones) {
            modelo1.addElement(tem);
        }

        mensajes_mensajes.setModel(modelo1);
    }//GEN-LAST:event_jButton7MouseClicked

    private void usuario_listasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuario_listasMouseClicked
      if (evt.isMetaDown()) {
            ppm_bloquear_usuario.show(evt.getComponent(), evt.getX(),evt.getY());
            index_b_usuario = usuario_listas.getSelectedIndex();
        }
    }//GEN-LAST:event_usuario_listasMouseClicked

    private void mensajes_mensajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mensajes_mensajesMouseClicked
       if (evt.isMetaDown()) {
            ppm_bloquear_mensajes.show(evt.getComponent(), evt.getX(),evt.getY());
            index_b_publicacion = mensajes_mensajes.getSelectedIndex();
        }
    }//GEN-LAST:event_mensajes_mensajesMouseClicked

    private void arbol_solicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbol_solicitudesMouseClicked
     if (evt.isMetaDown()) {
            ppm_solicitudes.show(evt.getComponent(),evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_arbol_solicitudesMouseClicked

    private void agregar_amigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_amigoActionPerformed
           
       
        Object v1 = arbol_solicitudes.getSelectionPath().getLastPathComponent();  
       
           
       DefaultTreeModel m = (DefaultTreeModel) arbol_amigos.getModel();
       DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
       DefaultMutableTreeNode amigos = new DefaultMutableTreeNode(v1);
       raiz.add(amigos);
       m.reload();
     
       
    
       
       
    }//GEN-LAST:event_agregar_amigoActionPerformed

    private void arbol_amigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbol_amigosMouseClicked
         if (evt.isMetaDown()) {
            ppm_amigos.show(evt.getComponent(),evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_arbol_amigosMouseClicked

    private void eliminar_amigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_amigoActionPerformed
       Object v1 = arbol_amigos.getSelectionPath().getLastPathComponent();
       DefaultTreeModel m = (DefaultTreeModel) arbol_amigos.getModel();
       arbol_amigos.getSelectionModel().removeSelectionPath(arbol_amigos.getSelectionPath());
       m.reload();
    }//GEN-LAST:event_eliminar_amigoActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
     JFileChooser fc = new JFileChooser();
       FileFilter filtro = new FileNameExtensionFilter("Imagenes","png,","jpg","jpeg","gif");
       fc.setFileFilter(filtro);
       File archivo;
       int op = fc.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            archivo = fc.getSelectedFile();
            Image img = Toolkit.getDefaultToolkit().createImage(archivo.getPath()).getScaledInstance(200, 217, 0);
            this.m_imagen.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
    tempo_n.get(index_usuario_normal).setNombre(m_nombre.getText());
    tempo_n.get(index_usuario_normal).setNombre_usuario(m_usuario.getText());//Nombre_usuario();//Nombre(m_nombre.getText());
    tempo_n.get(index_usuario_normal).setFecha_naciomiento(m_date.getDate());//Nombre(m_nombre.getText());
    tempo_n.get(index_usuario_normal).setCorreo(m_correo.getText());
    tempo_n.get(index_usuario_normal).setContraseña(m_contraseña.getText()); //Nombre(m_nombre.getText());
    tempo_n.get(index_usuario_normal).setFoto(m_imagen.getIcon());
    
    JOptionPane.showMessageDialog(usuario_normal,"Sus datos han sido modificado con exito");
    }//GEN-LAST:event_jButton10MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    tempo_n.get(index_b_usuario).setEstado(2);
    JOptionPane.showMessageDialog(usuario_administrador, "usuario bloqueado");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      tempo_publicaciones.get(index_b_publicacion).setEstado(2);
      JOptionPane.showMessageDialog(usuario_administrador, "Mensaje bloqueado");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
      DefaultTreeModel m = (DefaultTreeModel) mis_publicaciones.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
                abun.cargarArchivo();
                ArrayList<publicacion> tem = new ArrayList();
                tem = abun.getU_normal().get(index_usuario_normal).getPublicaciones();
                for (publicacion u : tem) {
                    DefaultMutableTreeNode amigos = new DefaultMutableTreeNode(u);
                    raiz.add(amigos);
                }
                m.reload();
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        abun.cargarArchivo();
        ArrayList<usuario_normal> us = new ArrayList();
        us = abun.getU_normal();
        us.remove(index_usuario_normal);
        abun.setU_normal(us);
        try {
            abun.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(usuario_normal,"Su usuario ha sido eliminado");
    }//GEN-LAST:event_jButton13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton admin;
    private javax.swing.JMenuItem agregar_amigo;
    private javax.swing.JDialog agregar_comentario;
    private javax.swing.JDialog agregar_problema;
    private javax.swing.JDialog agregar_respuesta;
    private javax.swing.JRadioButton amigos;
    private javax.swing.JTree arbol_amigos;
    private javax.swing.JTree arbol_solicitudes;
    private javax.swing.JTextArea area_comentario;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser date_chooser;
    private javax.swing.JMenuItem eliminar_amigo;
    private javax.swing.JMenuItem enviar_comentario;
    private javax.swing.JMenuItem enviar_problema;
    private javax.swing.JMenuItem enviar_respuesta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JPasswordField l_contraseña;
    private javax.swing.JTextField l_nombre;
    private javax.swing.JList<String> lista_publicaciones;
    private javax.swing.JTextField m_contraseña;
    private javax.swing.JTextField m_correo;
    private com.toedter.calendar.JDateChooser m_date;
    private javax.swing.JLabel m_imagen;
    private javax.swing.JTextField m_nombre;
    private javax.swing.JTextField m_usuario;
    private javax.swing.JList<String> mensajes_mensajes;
    private javax.swing.JTree mis_publicaciones;
    private javax.swing.JRadioButton normal;
    private javax.swing.JPopupMenu ppm_amigos;
    private javax.swing.JPopupMenu ppm_bloquear_mensajes;
    private javax.swing.JPopupMenu ppm_bloquear_usuario;
    private javax.swing.JPopupMenu ppm_publicacion;
    private javax.swing.JPopupMenu ppm_solicitudes;
    private javax.swing.JRadioButton privado;
    private javax.swing.JRadioButton publico;
    private javax.swing.JTextField r_contraseña;
    private javax.swing.JTextField r_correo;
    private javax.swing.JLabel r_foto;
    private javax.swing.JTextField r_nombre;
    private javax.swing.JTextField r_usuario;
    private javax.swing.JTextArea text_area;
    private javax.swing.JFrame usuario_administrador;
    private javax.swing.JList<String> usuario_listas;
    private javax.swing.JFrame usuario_normal;
    // End of variables declaration//GEN-END:variables

    
//private void cargar_publicaciones(){
//    
//}    
    
    
ArrayList<usuario_normal> us = new ArrayList();
ArrayList<usuario_administrador> ua = new ArrayList();
////
administrador_binario_usuarios abu = new administrador_binario_usuarios("./administradores.txt"); 
administrador_binario_usuario_normal abun = new administrador_binario_usuario_normal("./normales.txt"); 
administrador_publicaciones ap = new administrador_publicaciones("./publicaciones.txt"); 
////
String usuario_defecto =  "alexy123";
String contraseña = "buenas_tardes!";

///
int index_usuario_normal=0;
int index_usuario_admin=0;
//
ArrayList<usuario_administrador> tempo_a = new ArrayList();
ArrayList<usuario_normal> tempo_n = new ArrayList();
ArrayList<publicacion> tempo_publicaciones = new ArrayList();
 //
int index_b_usuario=0;
int index_publicacion = 0;
//
int index_b_publicacion = 0;

}
